layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

  # projects:
#   sort_by: pushed
#   # sort_by options:
#   #   - pushed
#   #   - stars
#   limit: 9
#   exclude:
#     forks: true
#     projects:
#     # - repo-name

social_media:
  medium: "@taggatle"
  twitter: "taggatle"

topics:
    
  - name: Machine Learning
    image_url: https://upload.wikimedia.org/wikipedia/commons/d/d5/Hey_Machine_Learning_Logo.png
  
  - name: Computer Vision
    image_url: https://upload.wikimedia.org/wikipedia/commons/e/e3/Zoom_prinzip.gif
    
  - name: Image Processing
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Transformation_%28after%29.png/748px-Transformation_%28after%29.png
  

repositories:
  - Real-time-multi-style-transfer
  - Smartphone-Software-Retina
  # - pysc2-reinforcement-learning-agents
  - history-of-gans
  - ImageCaptioningWithAttention
  # - ImageCaptioning
  - LensDistortionCorrection
  - TissueMicroarrayClassifier