layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  medium: "@taggatle"
  twitter: "taggatle"

topics:
  - name: PyTorch
    web_url: https://github.com/topics/pytorch
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
  
  - name: TensorFlow
    web_url: https://github.com/topics/tensorflow
    image_url:https://avatars0.githubusercontent.com/u/15658638?s=200&v=4
    
  - name: Machine Learning
  
  - name: Computer Vision
  
  - name: Image Processing
  
  
